"""
Django settings for services project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l$oi^2_df4it$h!!xv5px70y&=zuvn)#3rk4jx9x1)ifrr)4le'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Встроенные Django-приложения (всегда в начале)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Сторонние библиотеки (REST API, аутентификация и прочее)
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth.registration',
    'allauth.mfa',

    # Кастомные приложения (созданные тобой)
    'accaunts',  
    #'accaunts.apps.AccauntsConfig',  # Прописаваем apps чтобы он сделал привильные импорты
]



SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'services.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'services.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
        'HOST': os.environ.get('DB_HOST'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_USE_JWT = True



# Настройка обязательного подтверждения email
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Требует подтверждения email
ACCOUNT_EMAIL_REQUIRED = True  # Требует указания email при регистрации
ACCOUNT_USERNAME_REQUIRED = True  # Требует указания username при регистрации
ACCOUNT_AUTHENTICATION_METHOD = "email"  # Вход только через email
# ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1  # Указавает через сколько исякнет годность письма на почту
ACCOUNT_EMAIL_NOTIFICATIONS = True  # Указавает будет ли переход по ссылки озночать подверждения почту если True а если False то переадрисация и захождения будет значить подверждения
# ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = True  # Если True то оптравиться код для подверждения если False то будет отправляться ссылка
# ACCOUNT_EMAIL_VERIFICATION_BY_CODE_TIMEOUT = 300 А это мы указаваем сколько будет жить код который мы отправиляли на строчкой высше
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_MAX_ATTEMPTS = 5
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False  # Пользователи входят сразу после подвердения почты в аккаунд
ACCOUNT_LOGIN_TIMEOUT = 300  # Время в секундах сколько пользователю будет дано на каждый шаг
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True  # Определяет будет ли пользователь выведен из системы при сбросе пароля автоматически
ACCOUNT_SESSION_REMEMBER = True  # Делает чтобы пользователя запоминали когда он входил
ACCOUNT_SIGNUP_FORM_HONEYPOT_FIELD = "address"  # Обманка для спам ботов чтобы они вводили поле которые не видно в интерфейсе но они будут его автоматически вводить
                                                # (Не работает на хороших ботов но как одна из мер защиты подходит)
                                                
ACCOUNT_CHANGE_EMAIL = True  # Пользователь может иметь одну почту на один аккаунт

ACCOUNT_CONFIRM_EMAIL_ON_GET = True
                                        
ACCOUNT_EMAIL_CONFIRMATION_URL = 'accounts/confirm-email/{key}/' 

REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'dj_rest_auth.registration.serializers.RegisterSerializer',
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'famas.god1231@gmail.com'  # Твой Gmail адрес
EMAIL_HOST_PASSWORD = 'ffvw vbhz izgy brxh'  # Пароль приложения (не твой обычный пароль!)
DEFAULT_FROM_EMAIL = 'famas.god1231@gmail.com'

# MFA_RECOVERY_CODE_COUNT = 4
# MFA_WEBAUTHN_ALLOW_INSECURE_ORIGIN = True  # По дефолту localhost принимаяться здесь за небезопасную прогу
                                           # Чтобы временно это отключить изпользуеться эта команда
                                           # При окончания тестирования и начатия деплоить отключить


                                           
CELERY_BROKER_URL = 'redis://redis:6379/0'  # Тут мы делаем подключениямся к брокеру для хранения задач(Сам celery задачи не хранит) и указаваем тут строктуру
                                            # Тут мы указаваем redis redis потомучто работем в докере где redis у нас буквально так и называеться
                                            # Если бы тут работали без докера то писали бы так CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
                                
LOGGING = {
    'version' : 1,
    'handlers' : {
        'console': {'class' : 'logging.StreamHandler'}
    },
    'loggers': {
        'django.db.backends' : {
            'handlers': ['console'],
            'level' : 'DEBUG'
        }
    }
}  # С помощью этого мы видим запросы в бд в консоле