# Generated by Django 4.2.19 on 2025-04-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accaunts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_informations',
        ),
    ]
