# Generated by Django 4.2.19 on 2025-04-27 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accaunts', '0002_delete_user_informations'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_informations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
